name: 'SQLDef Preview'
description: 'Preview database schema migrations using sqldef tools'
author: 'FUJI Goro'

branding:
  icon: 'database'
  color: 'blue'

inputs:
  database-type:
    description: 'Database type (mysql, postgresql, sqlite3, mssql)'
    required: true

  schema-file:
    description: 'Path to the schema file'
    required: true
    default: 'schema.sql'

  base-branch:
    description: 'Base branch to compare against'
    required: false
    default: 'main'

  sqldef-version:
    description: 'Version of sqldef to use'
    required: false
    default: 'v3.0.0'

  # Database connection parameters - MySQL
  mysql-host:
    description: 'MySQL host'
    required: false
    default: '127.0.0.1'

  mysql-port:
    description: 'MySQL port'
    required: false
    default: '3306'

  mysql-user:
    description: 'MySQL user'
    required: false
    default: 'root'

  mysql-password:
    description: 'MySQL password'
    required: false

  mysql-database:
    description: 'MySQL database name'
    required: false

  # Database connection parameters - PostgreSQL
  postgresql-host:
    description: 'PostgreSQL host'
    required: false
    default: '127.0.0.1'

  postgresql-port:
    description: 'PostgreSQL port'
    required: false
    default: '5432'

  postgresql-user:
    description: 'PostgreSQL user'
    required: false
    default: 'postgres'

  postgresql-password:
    description: 'PostgreSQL password'
    required: false

  postgresql-database:
    description: 'PostgreSQL database name'
    required: false

  # Database connection parameters - SQLite3
  sqlite3-file:
    description: 'SQLite3 database file path'
    required: false
    default: 'database.sqlite3'

  # Database connection parameters - SQL Server
  mssql-host:
    description: 'SQL Server host'
    required: false
    default: '127.0.0.1'

  mssql-port:
    description: 'SQL Server port'
    required: false
    default: '1433'

  mssql-user:
    description: 'SQL Server user'
    required: false

  mssql-password:
    description: 'SQL Server password'
    required: false

  mssql-database:
    description: 'SQL Server database name'
    required: false

  # Additional options
  enable-drop:
    description: 'Enable destructive changes (DROP operations)'
    required: false
    default: 'false'

  config-file:
    description: 'Path to YAML configuration file'
    required: false

  github-token:
    description: 'GitHub token for commenting on PR'
    required: false
    default: ${{ github.token }}

outputs:
  migration-plan:
    description: 'The migration plan generated by sqldef --dry-run'

  has-changes:
    description: 'Whether there are any schema changes'

runs:
  using: 'node20'
  main: 'dist/index.js'